"""Generate draft handoff documents (``oss-continuity init``).

Principle: never invent information. Drafts contain only (a) facts derived from
repository evidence, each naming its source, and (b) explicit questions marked
"Needs maintainer input". Every draft carries a marker comment so later analyses
report it as unfinished until a maintainer completes it and removes the marker.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from . import __version__
from .analyzers.common import DRAFT_MARKER, MANIFESTS, find_doc, workflow_files
from .analyzers.operations import find_secrets
from .analyzers.releases import CHANGELOG_NAMES, detect_publishing
from .model import Report, Status
from .source import Release, RepoSource, SourceUnavailable, prefer_version_tags

NEEDS = "**Needs maintainer input**"


@dataclass
class DraftContext:
    source: RepoSource
    report: Report
    planned: set[str]


@dataclass
class DraftResult:
    artifact: str
    path: Path | None
    action: str  # created | overwritten | exists | would-create | unsupported
    note: str = ""


def _banner(ctx: DraftContext) -> list[str]:
    return [
        DRAFT_MARKER,
        f"> ⚠️ **Draft generated by OSS Continuity {__version__} on {ctx.report.generated_at[:10]}.**",
        "> Facts below were derived from repository evidence and name their source.",
        f"> Anything marked {NEEDS} could not be determined from the repository and must be",
        "> written by a maintainer. When the document is complete, delete this notice and the",
        "> `oss-continuity:draft` marker comment above it.",
        "",
    ]


def _releases(source: RepoSource) -> list[Release]:
    try:
        return prefer_version_tags(source.releases())
    except SourceUnavailable:
        return []


def _exists(source: RepoSource, name: str) -> bool:
    return bool(source.find(name, f".github/{name}", f"docs/{name}"))


# ---------------------------------------------------------------------------
HANDOFF_DOCS = [
    ("MAINTAINER.md", "who maintains the project and who the backup is"),
    ("RELEASE.md", "how to cut and publish a release"),
    ("DEVELOPMENT.md", "how to set up a development environment"),
    ("ARCHITECTURE.md", "how the code is organised"),
    ("CONTRIBUTING.md", "how changes are proposed and reviewed"),
    ("SECURITY.md", "how vulnerabilities are reported"),
]


def build_continuity(ctx: DraftContext) -> str:
    r = ctx.report
    lines = [
        f"# Project Continuity: {r.repository}",
        "",
        *_banner(ctx),
        "This document tells a future maintainer what they need to take over the project.",
        "",
        "## Current continuity status",
        "",
        f"_Source: `oss-continuity analyze` on {r.generated_at[:10]}._",
        "",
        "| Area | Check | Status | Result |",
        "|---|---|---|---|",
    ]
    for s in r.sections:
        for c in s.checks:
            lines.append(f"| {s.title} | {c.label} | {c.status.value} | {c.summary} |")
    lines += [
        "",
        "## Project status",
        "",
        NEEDS,
        "",
        "- [ ] Is the project active, maintenance-only, or seeking new maintainers?",
        "- [ ] Who is the designated backup maintainer?",
        "- [ ] If every maintainer becomes unreachable, who may grant access or transfer "
        "the project, and after how long?",
        "",
        "## Handoff documents",
        "",
    ]
    for name, purpose in HANDOFF_DOCS:
        if _exists(ctx.source, name):
            state = "present"
        elif name in ctx.planned:
            state = "draft generated by `oss-continuity init`"
        else:
            state = "missing"
        lines.append(f"- [{name}]({name}): {purpose} ({state})")
    lines += [
        "",
        "## Access a successor needs",
        "",
        f"{NEEDS}: confirm each item and record who currently holds it.",
        "",
        "- [ ] Admin access to the source repository",
    ]
    for path, label in detect_publishing(ctx.source):
        lines.append(f"- [ ] Credentials or ownership needed for **{label}** (used in `{path}`)")
    for name, paths in sorted(find_secrets(ctx.source).items()):
        lines.append(f"- [ ] CI secret `{name}` (referenced in {', '.join(f'`{p}`' for p in paths)})")
    lines += [
        "- [ ] Package registry ownership, if the project is published",
        "- [ ] Domains, documentation hosting and other external services, if any",
        "",
    ]
    return "\n".join(lines)


def build_maintainer(ctx: DraftContext) -> str:
    facts = ctx.report.facts
    lines = [
        "# Maintainers",
        "",
        *_banner(ctx),
        "## Current maintainers",
        "",
        NEEDS,
        "",
        "| Name | Handle | Responsibilities | Since |",
        "|---|---|---|---|",
        "| _Needs maintainer input_ | | | |",
        "",
        "**Backup maintainer:** _Needs maintainer input_",
        "",
        "## Observed committers",
        "",
    ]
    top = facts.get("top_committers") or []
    if top:
        lines += [
            f"_Source: commit history, last {facts.get('commit_window_days')} days, "
            "bots excluded. Commit authorship is not the same as maintainer rights: "
            "confirm each person's role before listing them above._",
            "",
            "| Person | Commits | Share |",
            "|---|---|---|",
        ]
        lines += [f"| {c['name']} (`{c['identity']}`) | {c['commits']} | {c['share']:.0%} |" for c in top]
    else:
        lines.append("_Commit history was not available when this draft was generated._")
    lines += ["", "## Credentials and secrets", ""]
    secrets = find_secrets(ctx.source)
    if secrets:
        lines.append("_Source: CI configuration files._")
        lines.append("")
        for name, paths in sorted(secrets.items()):
            lines.append(
                f"- `{name}`: referenced in {', '.join(f'`{p}`' for p in paths)}. "
                f"{NEEDS}: what it is, who owns it, how to rotate it."
            )
    else:
        lines.append(
            "No custom CI secrets were detected. "
            + NEEDS
            + ": list any other credentials (registries, domains, hosting)."
        )
    lines += [
        "",
        "## Becoming a maintainer",
        "",
        NEEDS,
        "",
        "- How are maintainers added and removed?",
        "- What permissions does a new maintainer receive, and from whom?",
        "",
    ]
    return "\n".join(lines)


def build_release(ctx: DraftContext) -> str:
    src = ctx.source
    facts: list[str] = []
    rels = _releases(src)
    if rels:
        newest = rels[0]
        origin = "GitHub releases" if newest.kind == "release" else "git tags"
        date = f" ({newest.date.date().isoformat()})" if newest.date else ""
        facts.append(f"- Latest release: `{newest.tag}`{date}. _Source: {origin}._")
        facts.append(f"- Recent tags: {', '.join(f'`{r.tag}`' for r in rels[:5])}. _Source: {origin}._")
    publishing = detect_publishing(src)
    for path, label in publishing:
        facts.append(f"- Publishing automation: {label} in `{path}`. _Source: workflow file._")
    changelogs = find_doc(src, CHANGELOG_NAMES, dirs=("", "docs/"))
    for p in changelogs:
        facts.append(f"- Changelog: `{p}`. _Source: file tree._")
    version_files = src.find(
        "pyproject.toml",
        "setup.py",
        "setup.cfg",
        "package.json",
        "Cargo.toml",
        "pom.xml",
        "build.gradle",
        "build.gradle.kts",
        "VERSION",
        "version.txt",
    )
    if version_files:
        facts.append(
            f"- Files that commonly declare the version: "
            f"{', '.join(f'`{p}`' for p in version_files)}. _Source: file tree._"
        )

    lines = ["# Release Process", "", *_banner(ctx), "## What the repository shows", ""]
    if not (rels or publishing or changelogs):
        lines += [
            "The repository does not currently contain enough information to determine "
            "the official release procedure.",
            "",
        ]
    lines += facts
    lines += [
        "",
        "## Information required from maintainers",
        "",
        NEEDS,
        "",
        "- Who can publish releases?",
        "- How are version numbers chosen?",
        "- How is the changelog updated?",
    ]
    if publishing:
        lines.append(
            "- Confirm the workflow(s) above are the official publishing path, and what triggers them."
        )
    else:
        lines.append("- Which CI workflow, or whose machine, publishes packages?")
    lines += [
        "- What must be checked before a release (tests, docs, migration notes)?",
        "- How is a broken release yanked or rolled back?",
        "",
        "## Release steps",
        "",
        NEEDS,
        "",
        "1. _…_",
        "",
    ]
    return "\n".join(lines)


def build_architecture(ctx: DraftContext) -> str:
    paths = ctx.source.paths()
    dirs = Counter(p.split("/", 1)[0] for p in paths if "/" in p)
    root_files = [p for p in paths if "/" not in p]
    lines = [
        "# Architecture",
        "",
        *_banner(ctx),
        "## Repository layout",
        "",
        f"_Source: file tree ({len(paths)} files scanned)._",
        "",
    ]
    if dirs:
        lines += ["| Directory | Files |", "|---|---|"]
        lines += [f"| `{d}/` | {n} |" for d, n in sorted(dirs.items())[:40]]
        lines.append("")
    if root_files:
        lines.append("Top-level files: " + ", ".join(f"`{f}`" for f in root_files[:20]))
        lines.append("")
    manifests = ctx.source.find(*MANIFESTS)
    if manifests:
        lines += ["## Detected build and packaging files", "", "_Source: file tree._", ""]
        lines += [
            f"- `{m}`: {MANIFESTS[Path(m).name] if Path(m).name in MANIFESTS else 'build file'}"
            for m in manifests
        ]
        lines.append("")
    for heading, question in [
        ("Overview", "What does the system do, at a high level?"),
        ("Main components", "What are the main modules or packages, and what is each responsible for?"),
        ("Data and control flow", "How do requests or data move through the components?"),
        ("Key design decisions", "Which decisions matter most, and why were they made?"),
        ("Fragile or surprising areas", "What should a new maintainer be careful with?"),
    ]:
        lines += [f"## {heading}", "", f"{NEEDS}: {question}", ""]
    return "\n".join(lines)


def _make_targets(text: str) -> list[str]:
    targets = re.findall(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)\s*:(?!=)", text, re.MULTILINE)
    return list(dict.fromkeys(targets))[:15]


def build_development(ctx: DraftContext) -> str:
    src = ctx.source
    lines = [
        "# Development Setup",
        "",
        *_banner(ctx),
        "## Detected tooling",
        "",
        "_Source: file tree and the files named below._",
        "",
    ]
    found = False
    for m in src.find(*MANIFESTS):
        found = True
        lines.append(f"- `{m}`: {MANIFESTS.get(Path(m).name, 'build file')}")
    for mk in src.find("Makefile"):
        targets = _make_targets(src.read_text(mk) or "")
        if targets:
            lines.append(f"  - Make targets in `{mk}`: {', '.join(f'`{t}`' for t in targets)}")
    for pj in src.find("package.json"):
        try:
            scripts = json.loads(src.read_text(pj) or "{}").get("scripts") or {}
        except (ValueError, AttributeError):
            scripts = {}
        if scripts:
            lines.append(f"  - npm scripts in `{pj}`: {', '.join(f'`{s}`' for s in list(scripts)[:15])}")
    ci = workflow_files(src)
    if ci:
        found = True
        lines.append(
            "- CI configuration (shows how the project is built and tested in automation): "
            + ", ".join(f"`{p}`" for p in ci)
        )
    if not found:
        lines.append("No build tooling or CI configuration was detected.")
    lines.append("")
    for heading, question in [
        ("Prerequisites", "Which toolchains and versions are required?"),
        ("Install dependencies", "What are the exact commands?"),
        ("Run the tests", "How are tests (and linters/formatters) run locally?"),
        ("Configuration", "Which environment variables, services or test data are needed?"),
    ]:
        lines += [f"## {heading}", "", f"{NEEDS}: {question}", ""]
    return "\n".join(lines)


def build_contributing(ctx: DraftContext) -> str:
    src = ctx.source
    lines = ["# Contributing", "", *_banner(ctx), "## What the repository shows", ""]
    facts = []
    if src.match(r"\.github/ISSUE_TEMPLATE/.+") or src.find(".github/ISSUE_TEMPLATE.md"):
        facts.append("- Issue templates exist in `.github/`. _Source: file tree._")
    pr = src.find(
        ".github/PULL_REQUEST_TEMPLATE.md", "PULL_REQUEST_TEMPLATE.md", "docs/PULL_REQUEST_TEMPLATE.md"
    )
    if pr:
        facts.append(f"- Pull request template: `{pr[0]}`. _Source: file tree._")
    lic = src.match(r"(licen[cs]e|copying)([-._][^/]*)?")
    if lic:
        facts.append(f"- License file: `{lic[0]}`. _Source: file tree._")
    if _exists(src, "DEVELOPMENT.md") or "DEVELOPMENT.md" in ctx.planned:
        facts.append("- Development setup: see [DEVELOPMENT.md](DEVELOPMENT.md).")
    lines += facts or ["No contribution-related files were detected."]
    lines += [
        "",
        "## How to contribute",
        "",
        NEEDS,
        "",
        "- Should contributors open an issue before a pull request?",
        "- What code style, commit message and review expectations apply?",
        "- Is a DCO sign-off or CLA required?",
        "- How long should contributors expect to wait for review?",
        "",
    ]
    return "\n".join(lines)


def build_codeowners(ctx: DraftContext) -> str:
    top = ctx.report.facts.get("top_committers") or []
    lines = [
        "# oss-continuity:draft",
        f"# CODEOWNERS draft generated by OSS Continuity {__version__}.",
        "# It has NO active rules until you add them: GitHub ignores comment lines.",
        "# Syntax: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners",
        "#",
    ]
    if top:
        lines.append(
            f"# Observed top committers (source: commit history, last "
            f"{ctx.report.facts.get('commit_window_days')} days). Commit authorship is not"
        )
        lines.append("# ownership: confirm with each person before listing them.")
        for c in top[:5]:
            handle = f"@{c['identity']}" if "@" not in c["identity"] else c["identity"]
            lines.append(f"#   {handle}  ({c['name']}, {c['commits']} commits)")
    else:
        lines.append("# Commit history was not available when this draft was generated.")
    lines += [
        "#",
        "# Example (replace with real owners, then uncomment):",
        "# *            @owner-one @owner-two",
        "# /docs/       @docs-owner",
        "",
    ]
    return "\n".join(lines)


BUILDERS: dict[str, tuple[str, Callable[[DraftContext], str]]] = {
    "CONTINUITY.md": ("CONTINUITY.md", build_continuity),
    "MAINTAINER.md": ("MAINTAINER.md", build_maintainer),
    "RELEASE.md": ("RELEASE.md", build_release),
    "DEVELOPMENT.md": ("DEVELOPMENT.md", build_development),
    "ARCHITECTURE.md": ("ARCHITECTURE.md", build_architecture),
    "CONTRIBUTING.md": ("CONTRIBUTING.md", build_contributing),
    "CODEOWNERS": (".github/CODEOWNERS", build_codeowners),
}

NO_TEMPLATE = {
    "LICENSE": "choose a license yourself (https://choosealicense.com); it cannot be inferred",
    "SECURITY.md": "needs a real private reporting channel, which cannot be inferred",
    "README.md": "describe the project in your own words",
    "CHANGELOG.md": "start one with real release notes (https://keepachangelog.com)",
}


def plan(report: Report, only: list[str] | None = None) -> list[str]:
    wanted = list(only) if only else report.missing_artifacts()
    cont = report.check("continuity_doc")
    if not only and "CONTINUITY.md" not in wanted and cont and cont.status is not Status.PASS:
        wanted.append("CONTINUITY.md")
    order = list(BUILDERS) + [w for w in wanted if w not in BUILDERS]
    return [w for w in order if w in wanted]


def generate_drafts(
    source: RepoSource,
    report: Report,
    out_dir: Path,
    *,
    only: list[str] | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> list[DraftResult]:
    names = plan(report, only)
    results: list[DraftResult] = []
    unsupported: list[DraftResult] = []
    to_build: list[tuple[str, Path, Callable[[DraftContext], str]]] = []
    for name in names:
        if name not in BUILDERS:
            unsupported.append(
                DraftResult(name, None, "unsupported", NO_TEMPLATE.get(name, "no draft template available"))
            )
            continue
        rel, builder = BUILDERS[name]
        target = out_dir / rel
        if target.exists() and not force:
            results.append(DraftResult(name, target, "exists", "use --force to overwrite"))
            continue
        to_build.append((name, target, builder))

    ctx = DraftContext(source, report, planned={n for n, _, _ in to_build})
    for name, target, builder in to_build:
        if dry_run:
            results.append(DraftResult(name, target, "would-create"))
            continue
        existed = target.exists()
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(builder(ctx), encoding="utf-8")
        results.append(DraftResult(name, target, "overwritten" if existed else "created"))
    return results + unsupported
