from __future__ import annotations

from ..model import Report, Status
from .text import summary_line

MD_SYMBOLS = {Status.PASS: "✅", Status.WARN: "⚠️", Status.FAIL: "❌", Status.INFO: "ℹ️", Status.UNKNOWN: "❔"}


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_markdown(report: Report, *, emoji: bool = True) -> str:
    out = [
        f"# OSS Continuity Report: `{report.repository}`",
        "",
        f"- **Source:** {report.source} ({report.location})",
        f"- **Generated:** {report.generated_at} by oss-continuity {report.tool_version}",
        f"- **Checks:** {summary_line(report)}",
        "",
    ]
    for section in report.sections:
        out += [f"## {section.title}", "", "| Status | Check | Result | Evidence |", "|---|---|---|---|"]
        for c in section.checks:
            status = MD_SYMBOLS[c.status] if emoji else c.status.value.upper()
            evidence = "<br>".join(_cell(e) for e in c.evidence)
            out.append(f"| {status} | {_cell(c.label)} | {_cell(c.summary)} | {evidence} |")
        out.append("")

    missing = report.missing_artifacts()
    out += ["## Handoff readiness", ""]
    out += [f"- `{m}`" for m in missing] if missing else ["No handoff artifacts are missing."]
    out.append("")
    actions = report.actions()
    if actions:
        out += ["## Recommended actions", ""]
        out += [f"{i}. {a}" for i, a in enumerate(actions, 1)]
        out.append("")
    out += [
        "---",
        "",
        "_No overall score is computed by design: every result above is backed by the "
        "listed evidence. Generated by oss-continuity._",
        "",
    ]
    return "\n".join(out)
